<x-settings-shell active="audit" title="Audit logs" description="Review management activity and security events across the system.">
    <header class="settings-section-heading"><div><span class="event-eyebrow">Immutable history</span><h2>Activity log</h2></div><button type="button" class="event-button-secondary" wire:click="export"><x-heroicon-o-arrow-down-tray />Export CSV</button></header>
    <div class="audit-filters">
        <label class="event-search"><x-heroicon-o-magnifying-glass /><span class="sr-only">Search logs</span><input type="search" wire:model.live.debounce.300ms="search" placeholder="Actor or description"></label>
        <label class="event-type-filter"><select wire:model.live="action"><option value="">All actions</option>@foreach($actions as $item)<option value="{{ $item }}">{{ Str::headline($item) }}</option>@endforeach</select><x-heroicon-o-chevron-down /></label>
        <label class="event-type-filter"><select wire:model.live="module"><option value="">All modules</option>@foreach($modules as $item)<option value="{{ $item }}">{{ Str::headline($item) }}</option>@endforeach</select><x-heroicon-o-chevron-down /></label>
        <label><span class="sr-only">From date</span><input type="date" wire:model.live="dateFrom"></label><label><span class="sr-only">To date</span><input type="date" wire:model.live="dateTo"></label>
    </div>
    <div class="audit-table-wrap"><table class="audit-table"><thead><tr><th>When</th><th>Actor</th><th>Activity</th><th>Module</th><th></th></tr></thead><tbody>@forelse($logs as $log)<tr><td><time datetime="{{ $log->created_at->toIso8601String() }}"><strong>{{ $log->created_at->format($churchSettings->date_format) }}</strong><small>{{ $log->created_at->format('g:i A') }}</small></time></td><td>{{ $log->actor?->name ?? 'System' }}</td><td><strong>{{ $log->description }}</strong><small>{{ Str::headline($log->action) }}</small></td><td><span class="group-tag-badge">{{ Str::headline($log->module) }}</span></td><td><button type="button" class="event-icon-button" wire:click="$set('selectedLogId', {{ $log->id }})" aria-label="View audit details"><x-heroicon-o-chevron-right /></button></td></tr>@empty<tr><td colspan="5"><div class="event-empty-state event-empty-compact"><h3>No matching activity</h3><p>Adjust the filters to review another part of the history.</p></div></td></tr>@endforelse</tbody></table></div>
    @if($logs->hasPages())<div class="event-pagination">{{ $logs->links() }}</div>@endif
    @if($selectedLog)<aside class="audit-detail"><header><div><span class="event-eyebrow">Audit #{{ $selectedLog->id }}</span><h3>{{ $selectedLog->description }}</h3></div><button type="button" wire:click="$set('selectedLogId', null)" aria-label="Close details"><x-heroicon-o-x-mark /></button></header><dl><div><dt>Actor</dt><dd>{{ $selectedLog->actor?->name ?? 'System' }}</dd></div><div><dt>IP address</dt><dd>{{ $selectedLog->ip_address ?: 'Unavailable' }}</dd></div><div><dt>Action</dt><dd>{{ Str::headline($selectedLog->action) }}</dd></div><div><dt>Module</dt><dd>{{ Str::headline($selectedLog->module) }}</dd></div></dl>@if($selectedLog->old_values)<div><h4>Before</h4><pre>{{ json_encode($selectedLog->old_values, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre></div>@endif @if($selectedLog->new_values)<div><h4>After</h4><pre>{{ json_encode($selectedLog->new_values, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre></div>@endif</aside>@endif
</x-settings-shell>
